<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
if ($block->getFormKeyProvider()->isFullPageCacheEnabled()):
    $mageInit = [
        'Magento_PageCache/js/form-key-provider' => [
            'isPaginationCacheEnabled' => (int) $block->getFormKeyProvider()->isPaginationCacheEnabled(),
        ],
    ];
    ?>
    <div hidden data-mage-init='<?= $block->escapeHtmlAttr(json_encode($mageInit, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT)) ?>'></div>
<?php endif; ?>
