<?php
/** @var \Local\HomepageAssets\Block\HomepageKratomProducts $block */

use Magento\Framework\App\Action\Action;

$_productCollection = $block->getProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$image = 'category_page_grid';
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $block->escapeHtml(__("We can't find products matching the selection.")) ?></div>
    </div>
<?php else: ?>
    <div class="block block-filterproducts">
        <div class="block-content">
            <div class="grid products-grid">
                <div class="owl-carousel owl-theme items product-items filterproducts">
                    <?php foreach ($_productCollection as $_product): ?>
                        <div class="item product product-item">
                            <div class="product-item-info" data-container="product-grid">
                                <div class="image-product">
                                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                       class="product photo product-item-photo"
                                       tabindex="-1">
                                        <?= $block->getImage($_product, $image)->toHtml() ?>
                                    </a>
                                </div>

                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                            <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                        </a>
                                    </strong>
                                    <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                    <?= /* @noEscape */ $block->getProductPrice($_product) ?>

                                    <div class="product-item-inner">
                                        <div class="product actions product-item-actions">
                                            <div class="actions-primary">
                                                <?php if ($_product->isSaleable()): ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                    <form data-role="tocart-form"
                                                          data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                          action="<?= /* @NoEscape */ $postParams['action'] ?>"
                                                          method="post">
                                                        <input type="hidden" name="product"
                                                               value="<?= $block->escapeHtmlAttr((string)$postParams['data']['product']) ?>">
                                                        <input type="hidden"
                                                               name="<?= $block->escapeHtmlAttr(Action::PARAM_NAME_URL_ENCODED) ?>"
                                                               value="<?= $block->escapeHtmlAttr((string)$postParams['data'][Action::PARAM_NAME_URL_ENCODED]) ?>">
                                                        <?= $block->getBlockHtml('formkey') ?>
                                                        <button type="submit"
                                                                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                class="action tocart primary">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    </form>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
