<?php
/**
 *
 * SM CartQuickPro - Version 1.0.0
 * Copyright (c) 2017 YouTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * Author: YouTech Company
 * Websites: http://www.magentech.com
 */

if (!(int)$this->_getConfig('isenabled', 1))
    return;

$_config            = $this->helper('Sm\Market\Helper\Data');
$productStyle       = $_config->getThemeLayout('layout_product/product_style');
$classListContainer = ', .product-item-info[data-container="product-list"] .image-product';
$customContainer    = ', .box-quickview, .box-quickview-inline';

/**
 * Default quickview button container
 */
$buttonContainer = '.product-item-info[data-container="product-grid"] .actions-secondary' . $classListContainer . $customContainer;

if ($productStyle == 'product-1') {
    $buttonContainer = '.product-item-info[data-container="product-grid"] .product-item-details' . $classListContainer . $customContainer;
}

if ($productStyle == 'product-8' || $productStyle == 'product-10') {
    $buttonContainer = '.product-item-info[data-container="product-grid"] .image-product' . $classListContainer . $customContainer;
}
if ($productStyle == 'product-23') {
	 $buttonContainer = '.product-item-info[data-container="product-grid"] .product-item-details .actions-primary'  . $classListContainer . $customContainer;
}

$mageInit = [
    'Sm_CartQuickPro/js/quickview-init' => [
        'isQuickView' => $this->_isQuickView(),
        'isAjaxCart' => $this->_isAjaxCart(),
        'product_container' => '.product-item',
        'button_container' => $buttonContainer,
        'label_button' => $this->_getConfig('label_button'),
        'base_url' => $this->getUrl(),
    ],
];
?>

<div hidden data-mage-init='<?= $block->escapeHtmlAttr(json_encode($mageInit, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT)) ?>'></div>
