<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var Magento\Framework\View\Element\Template $block
 */
?>
<div
    class="cookie-status-message"
    id="cookie-status"
    style="display:none;"
    data-mage-init='{"cookieStatus":{}}'
>
    <?= $block->escapeHtml(__('The store will not work correctly when cookies are disabled.')); ?>
</div>
