<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var $block \Magento\Customer\Block\CustomerScopeData */
$mageInit = [
    'Magento_Customer/js/invalidation-processor' => [
        'invalidationRules' => [
            'website-rule' => [
                'Magento_Customer/js/invalidation-rules/website-rule' => [
                    'scopeConfig' => [
                        'websiteId' => (string) $block->getWebsiteId(),
                    ],
                ],
            ],
        ],
    ],
];
?>
<div hidden data-mage-init='<?= $block->escapeHtmlAttr(json_encode($mageInit, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT)) ?>'></div>
