<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\ObjectManager;
use Magento\Customer\ViewModel\CookieSettings;

/** @var \Magento\Customer\Block\CustomerData $block */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
/** @var Auth $auth */
$auth = $block->getAuth() ?? ObjectManager::getInstance()->get(Auth::class);
/** @var JsonSerializer $jsonSerializer */
$jsonSerializer = $block->getJsonSerializer() ??
    ObjectManager::getInstance()->get(JsonSerializer::class);
$customerDataUrl = $block->getCustomerDataUrl('customer/account/updateSession');
$expirableSectionNames = $block->getExpirableSectionNames();
/** @var CookieSettings $cookieSettings */
$cookieSettings = $block->getCookieSettings();

$mageInit = [
    'Magento_Customer/js/customer-data' => [
        'sectionLoadUrl' => $block->getCustomerDataUrl('customer/section/load'),
        'expirableSectionLifetime' => (int) $block->getExpirableSectionLifetime(),
        'expirableSectionNames' => $expirableSectionNames,
        'cookieLifeTime' => (string) $block->getCookieLifeTime(),
        'cookieDomain' => (string) $cookieSettings->getCookieDomain(),
        'updateSessionUrl' => $customerDataUrl,
        'isLoggedIn' => (string) $auth->isLoggedIn(),
    ],
];
?>
<div hidden data-mage-init='<?= $block->escapeHtmlAttr(json_encode($mageInit, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT)) ?>'></div>
