<?php /** @var Sm\AutoCompleteSearch\Block\Autocomplete $block */ ?>
<?php
if ($block->escapeHtml($block->getSearchEnable()) == 0) {
    return;
}

$mageInit = [
    'Magento_Ui/js/core/app' => [
        'components' => [
            'smautocomplete_form' => [
                'component' => 'Sm_AutoCompleteSearch/js/autocomplete',
            ],
            'searchsuiteautocompleteBindEvents' => [
                'component' => 'Sm_AutoCompleteSearch/js/bindEvents',
                'config' => [
                    'searchFormSelector' => '#search_mini_form',
                    'searchButtonSelector' => 'button.search',
                    'inputSelector' => '#search, #mobile_search, .minisearch input[type="text"]',
                    'searchDelay' => (string) $block->getSearchDelay(),
                ],
            ],
            'searchsuiteautocompleteDataProvider' => [
                'component' => 'Sm_AutoCompleteSearch/js/dataProvider',
                'config' => [
                    'url' => $block->getSearchUrl(),
                ],
            ],
        ],
    ],
];
?>
<div
    data-bind="scope: 'smautocomplete_form'"
    data-mage-init='<?= $block->escapeHtmlAttr(json_encode($mageInit, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT)) ?>'
>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
