<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
$_post = $this->getPost();
$_postUrl = $_post->getPostUrl();
$_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<li class="post-holder post-holder-<?= (int)$_post->getId() ?>">
    <article class="post-content post-custom blog-card">
        <?php if ($featuredImage = $_post->getFeaturedImage()): ?>
            <a class="post-ftimg-hld" href="<?= $block->escapeUrl($_postUrl) ?>" title="<?= $_postName ?>">
                <img src="<?= $block->escapeUrl($featuredImage) ?>" alt="<?= $_postName ?>" />
            </a>
        <?php endif; ?>

        <div class="post-info-blog">
            <div class="post-header">
                <?= /* @noEscape */ $this->getInfoHtml() ?>
                <h2 class="post-title">
                    <a class="post-item-link" href="<?= $block->escapeUrl($_postUrl) ?>">
                        <?= /* @noEscape */ $_postName ?>
                    </a>
                </h2>
            </div>

            <div class="post-text-hld clearfix">
                <?= /* @noEscape */ $block->getShorContent() ?>
            </div>

            <a class="post-read-more" href="<?= $block->escapeUrl($_postUrl) ?>" title="<?= $_postName ?>">
                <?= $block->escapeHtml(__('Read article')) ?>
            </a>
        </div>
    </article>
</li>
